In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

C:\Users\hp\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


## Data Preprocessing 

### Importing Dataset 

In [2]:
dataset=pd.read_csv('C:/Users/hp/OneDrive/Documents/Vamsi/Python/Churn_Modelling_ANN/Churn_Modelling.csv')
X=dataset.iloc[:,3:-1].values
y=dataset.iloc[:,-1].values

### Encoding Categorical Data

#### Label Encoding to Gender Column

In [3]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
X[:,2]=le.fit_transform(X[:,2])

In [4]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


#### One Hot Encoding to Geography Column 

In [5]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder', OneHotEncoder(),[1])], remainder='passthrough')
X=np.asarray(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Spliting the dataset into training and test set

In [6]:
from sklearn.model_selection import train_test_split as tts
X_train,X_test,y_train,y_test=tts(X,y,test_size=0.2,random_state=0)

### Feature Scaling

In [7]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)

In [8]:
print(X_train)

[[-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   1.10643166]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -0.74866447]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.48533467]
 ...
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.41231994]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
   0.84432121]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   0.32472465]]


In [9]:
print(X_test)

[[-0.95692675  1.62776996 -0.57427105 ...  0.66011376  0.97628121
   1.62185911]
 [ 1.04501206 -0.61433742 -0.57427105 ...  0.66011376 -1.02429504
   0.504204  ]
 [-0.95692675 -0.61433742  1.74133801 ...  0.66011376  0.97628121
  -0.41865644]
 ...
 [-0.95692675 -0.61433742  1.74133801 ...  0.66011376 -1.02429504
   0.72775202]
 [-0.95692675  1.62776996 -0.57427105 ...  0.66011376  0.97628121
  -1.54162886]
 [-0.95692675  1.62776996 -0.57427105 ...  0.66011376 -1.02429504
   1.62356528]]


## Building ANN

### Initializing ANN

In [10]:
ann=tf.keras.models.Sequential()

### Adding input and first hidden layer 

In [11]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

### Adding second hidden layer

In [12]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

### Adding output layer

In [13]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

## Training the ANN 

### Compiling the ANN

In [14]:
ann.compile(optimizer='adam',loss='binary_crossentropy', metrics=['accuracy'])

### Training the ANN on the training set

In [15]:
ann.fit(X_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 639us/step - accuracy: 0.4592 - loss: 0.8735
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 627us/step - accuracy: 0.7924 - loss: 0.5143
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 597us/step - accuracy: 0.7963 - loss: 0.4711
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 630us/step - accuracy: 0.7959 - loss: 0.4549
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 625us/step - accuracy: 0.7926 - loss: 0.4486
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 617us/step - accuracy: 0.7949 - loss: 0.4430
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 627us/step - accuracy: 0.8009 - loss: 0.4342
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 613us/step - accuracy: 0.8064 - loss: 0.4360
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 652us/step - accuracy: 0.8252 - loss: 0.4129
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 595us/step - accuracy: 0.8171 - loss: 0.4176
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 614us/step - accuracy: 0.8275 - loss: 0.4038
Epoch 12/100
250/25

250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 731us/step - accuracy: 0.8582 - loss: 0.3332
Epoch 68/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 713us/step - accuracy: 0.8565 - loss: 0.3465
Epoch 69/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 760us/step - accuracy: 0.8564 - loss: 0.3512
Epoch 70/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 763us/step - accuracy: 0.8651 - loss: 0.3343
Epoch 71/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 740us/step - accuracy: 0.8600 - loss: 0.3365
Epoch 72/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 726us/step - accuracy: 0.8640 - loss: 0.3425
Epoch 73/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 735us/step - accuracy: 0.8560 - loss: 0.3454
Epoch 74/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 746us/step - accuracy: 0.8569 - loss: 0.3401
Epoch 75/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 734us/step - accuracy: 0.8556 - loss: 0.3461
Epoch 76/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 736us/step - accuracy: 0.8615 - loss: 0.3406
Epoch 77/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 739us/step - accuracy: 0.8596 - loss: 0.3388
Epoch 78/100
250/250 ━━

## Making Predictions and evaluating the model 

### Predicting the result of a single observation

In [16]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]])))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
[[0.02315675]]


In [17]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))>0.5)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
[[False]]


### Predicting the test set results

In [18]:
y_pred=ann.predict(X_test)
y_pred=(y_pred>0.5)
print(np.concatenate((y_pred.reshape(-1,1),y_test.reshape(-1,1)),1))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 684us/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making Confusion Matrix and Accuracy score 

In [19]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(y_pred,y_test)
print(cm)
accuracy_score(y_pred,y_test)

[[1517  200]
 [  78  205]]


0.861